export const studentsData = [
  {
    "No": 1,
    "Name": "Halima ibrahim",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Université",
    "Class": "1ere Année ",
    "Parents_Name": "Ibrahim mana",
    "Phone_number": "690141100",
    "Location_of_child": " bonaberi Douala",
    "Location_of_parents": "Bonaberi Douala"
  },
  {
    "No": 2,
    "Name": "Mariama dasso oumarou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary",
    "Class": "LSsc",
    "Parents_Name": "Oumarou ahmadou",
    "Phone_number": "",
    "Location_of_child": "Dla,bonaberi,ndobo",
    "Location_of_parents": "Dla,bonaberi.ndobo"
  },
  {
    "No": 3,
    "Name": "Mariama Dasso Oumarou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary",
    "Class": "LSsc",
    "Parents_Name": "Oumarou Ahmadou and Hadija mouhamad",
    "Phone_number": "",
    "Location_of_child": "Dla-Bonaberi-Ndobo",
    "Location_of_parents": "Dla-Bonaberi-Ndobo"
  },
  {
    "No": 4,
    "Name": "Halima sale",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary but stopped due to crises",
    "Class": "6",
    "Parents_Name": "Sale and hapsatou",
    "Phone_number": "",
    "Location_of_child": "binka",
    "Location_of_parents": "Binka"
  },
  {
    "No": 5,
    "Name": "AAISHATOU",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "High school",
    "Class": "Lower6",
    "Parents_Name": "KARIMU WAJIRI/RAMATU ADAMU",
    "Phone_number": "",
    "Location_of_child": "Yaounde",
    "Location_of_parents": "West, Dchang"
  },
  {
    "No": 6,
    "Name": "Kursumi umaru",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary e",
    "Class": "Level one in nursing",
    "Parents_Name": "Abdul mumini and Adamu Adamu",
    "Phone_number": "677383064",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 7,
    "Name": "Yunusa Hamidou",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "secondary",
    "Class": "left school in form2 in 2014",
    "Parents_Name": "Hamidou Adamu and Aminatou Manu",
    "Phone_number": "654969565",
    "Location_of_child": "Tiko",
    "Location_of_parents": "Binka"
  },
  {
    "No": 8,
    "Name": "Mohamadou Ibrahim mana",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "High school",
    "Class": "Upper sixth arts",
    "Parents_Name": "Ibrahim mana",
    "Phone_number": "654708612",
    "Location_of_child": "Ndobo Douala",
    "Location_of_parents": "Ndobo Douala"
  },
  {
    "No": 9,
    "Name": "Aissatou Doudou🌸",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Year 2",
    "Class": "Year 2 ",
    "Parents_Name": "MR KEHRI AMADOU",
    "Phone_number": "",
    "Location_of_child": "Bonaberi ",
    "Location_of_parents": "Bonaberi "
  },
  {
    "No": 10,
    "Name": "Musa Hayatou",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "University ",
    "Class": "Masters form ",
    "Parents_Name": "Musa Banu/ Musa Salamatu",
    "Phone_number": "654708612",
    "Location_of_child": "SW Buea ",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 11,
    "Name": "Yaouba Gibiri Manu",
    "Gender": "male",
    "Type_of_education": "Arabiya",
    "Level": "",
    "Class": "",
    "Parents_Name": "Manu Gibri Bayero",
    "Phone_number": "678321800",
    "Location_of_child": "Bertoua ",
    "Location_of_parents": "Tiko"
  },
  {
    "No": 12,
    "Name": "KARIMU BALKISU",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "High school",
    "Class": "Lower 6 ",
    "Parents_Name": "KARIMU WAJIRI",
    "Phone_number": "",
    "Location_of_child": "Dchang",
    "Location_of_parents": "Dchang"
  },
  {
    "No": 13,
    "Name": "Hadijatu karimu",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary school",
    "Class": "Class 6",
    "Parents_Name": "Karimu wajiri",
    "Phone_number": "",
    "Location_of_child": "Dchang",
    "Location_of_parents": "Dchang"
  },
  {
    "No": 14,
    "Name": "Saidu Manu",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Postgraduate (Masters)",
    "Class": "Level 600",
    "Parents_Name": "Manu Galdima",
    "Phone_number": "673538880",
    "Location_of_child": "Tiko/ Buea ",
    "Location_of_parents": "Tiko"
  },
  {
    "No": 15,
    "Name": "Fadimatu karimu",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary school",
    "Class": "Class 3",
    "Parents_Name": "Karimu wajiri",
    "Phone_number": "",
    "Location_of_child": "Dchang",
    "Location_of_parents": "Dchang"
  },
  {
    "No": 16,
    "Name": "Djamila Ahidjo amadou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Probatoire",
    "Class": "Première CG(comptabilité)",
    "Parents_Name": "Amadou Ahidjo",
    "Phone_number": "681153627",
    "Location_of_child": "Douala ",
    "Location_of_parents": "Douala"
  },
  {
    "No": 17,
    "Name": "Ibrahima Gibiri Manu",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "secondary",
    "Class": "Form three (3)",
    "Parents_Name": "Manu Gibri Bayero And Mairo Ndemsah",
    "Phone_number": "677864169",
    "Location_of_child": "Douala",
    "Location_of_parents": "Tiko"
  },
  {
    "No": 18,
    "Name": "Salifou Gibrila",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "secondary",
    "Class": "Form one ",
    "Parents_Name": "Julyatou Manu (mother)",
    "Phone_number": "697945800",
    "Location_of_child": "Tiko",
    "Location_of_parents": "Donga Mantung (Nkambe)"
  },
  {
    "No": 19,
    "Name": "Aishatou Gibiri Manu",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "secondary",
    "Class": "Form one",
    "Parents_Name": "Manu Gibri Bayero/ Mairo Ndemsah",
    "Phone_number": "678321800",
    "Location_of_child": "Tiko",
    "Location_of_parents": "Tiko"
  },
  {
    "No": 20,
    "Name": "Fadimatu karim",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Advance level",
    "Class": "Uppersixth",
    "Parents_Name": "Abdul karim",
    "Phone_number": "653710286",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 21,
    "Name": "Mohamadu Ibrahim mana",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "High School",
    "Class": "Upper sixth arts",
    "Parents_Name": "Ibrahim mana",
    "Phone_number": "697275992",
    "Location_of_child": "Ndobo Douala",
    "Location_of_parents": "Ndobo Douala"
  },
  {
    "No": 22,
    "Name": "Yaouba sabga",
    "Gender": "male",
    "Type_of_education": "Arabiya",
    "Level": "",
    "Class": "",
    "Parents_Name": "Abdou  kurgeh sabga ",
    "Phone_number": "674559062",
    "Location_of_child": "Douala letoral",
    "Location_of_parents": "Ndu sub division ,mbokop"
  },
  {
    "No": 23,
    "Name": "AMADOU ADAMOU",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "SECONDERY SCHOOL",
    "Class": "FORM TWO",
    "Parents_Name": "AMADOU",
    "Phone_number": "674666538",
    "Location_of_child": "SW R",
    "Location_of_parents": "YAOUNDE"
  },
  {
    "No": 24,
    "Name": "ABUBAKAR DAHIRU",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "PRIMARY SCHOOL",
    "Class": "CLASS ONE",
    "Parents_Name": "DAHIRU BIRI",
    "Phone_number": "674666538",
    "Location_of_child": "SWR",
    "Location_of_parents": "DOUALA"
  },
  {
    "No": 25,
    "Name": "Usmaila Abdoul Moumini",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "University",
    "Class": "Year 4",
    "Parents_Name": "Adama Adamu and Abdoul Moumini",
    "Phone_number": "674582289 and 677725307",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 26,
    "Name": "Mohammadou Abdoul Moumini",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "High school",
    "Class": "Upper sixth",
    "Parents_Name": "Adama Adamu and Abdoul Moumini",
    "Phone_number": "674582289 and 677725307",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 27,
    "Name": "Aishatou Abdoul Moumini",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary school",
    "Class": "form 2",
    "Parents_Name": "Adama Adamu and Abdoul Moumini",
    "Phone_number": "674582289 and 677725307",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 28,
    "Name": "Siwaybatou Juraisatou Abdoul Moumini",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Necessary school",
    "Class": "Necessary 1",
    "Parents_Name": "Adama Adamu and Abdoul Moumini",
    "Phone_number": "674582289 and 677725307",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 29,
    "Name": "Hawao-u Hassan",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "University",
    "Class": "Year one",
    "Parents_Name": "Hassan Ahmadou  and maimuna mohammadou",
    "Phone_number": "682173337",
    "Location_of_child": "Yaonde",
    "Location_of_parents": "Takijah"
  },
  {
    "No": 30,
    "Name": "Yawoba Amadou ",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Seconde´",
    "Class": "class seconde F3 ou électricité",
    "Parents_Name": "Ahmadou Ibrahim and Maïmonatu Adamou",
    "Phone_number": "699326535-662033939",
    "Location_of_child": "Yaounde´",
    "Location_of_parents": "Yaounde´"
  },
  {
    "No": 31,
    "Name": "Mohamadou Bashirou Ahmadou",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary",
    "Class": "classe deuxième année où 5eme maçonnerie",
    "Parents_Name": "Ahmadou Ibrahim and Maïmonatu Adamou",
    "Phone_number": "699326535-662033939",
    "Location_of_child": "Yaounde´",
    "Location_of_parents": "Yaounde´"
  },
  {
    "No": 32,
    "Name": "Aïchatou Ahmadou ",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 5",
    "Parents_Name": "Ahmadou Ibrahim and Maïmonatu Adamou ",
    "Phone_number": "699326535-662033939",
    "Location_of_child": "Yaounde´",
    "Location_of_parents": "Yaounde´"
  },
  {
    "No": 33,
    "Name": "Hassan Zuhaitou",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "Class six",
    "Parents_Name": "Hadija adamu and mallam Hassan",
    "Phone_number": "661080692",
    "Location_of_child": "Binka",
    "Location_of_parents": "Douala"
  },
  {
    "No": 34,
    "Name": "Mohammadou hardee",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "Class four",
    "Parents_Name": "Hadija adamu and mallam Hassan",
    "Phone_number": "661080692",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 35,
    "Name": "Aboubakar sidiki Hassan",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "Class one",
    "Parents_Name": "Hadija adamu and mallam Hassan",
    "Phone_number": "661080692",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 36,
    "Name": "Rachidatou Sali musa ",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary school ",
    "Class": "6e(form 1) ",
    "Parents_Name": "Bilkissou umarou ",
    "Phone_number": "675 14 15 29 ",
    "Location_of_child": "Douala ",
    "Location_of_parents": "Douala"
  },
  {
    "No": 37,
    "Name": "Mouhammad safiulah sali ",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Primary school ",
    "Class": "Class 2",
    "Parents_Name": "Bilkissou sali ",
    "Phone_number": "696 20 09 30",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala "
  },
  {
    "No": 38,
    "Name": "Aminatou Huseini",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "High School ",
    "Class": "Lowersixth",
    "Parents_Name": "Huseini Manu",
    "Phone_number": "670510703",
    "Location_of_child": "Douala",
    "Location_of_parents": "Takijah "
  },
  {
    "No": 39,
    "Name": "Mohamadou Ibrahim",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 6",
    "Parents_Name": "Shene musa and  Jeinabu abou",
    "Phone_number": "670315414",
    "Location_of_child": "Binka",
    "Location_of_parents": "Binka"
  },
  {
    "No": 40,
    "Name": "Fadimatou Jahara shene",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 2",
    "Parents_Name": "Shene musa and Jeinabu abou",
    "Phone_number": "670315414",
    "Location_of_child": "Binka",
    "Location_of_parents": "Binka"
  },
  {
    "No": 41,
    "Name": "Maimunatou shene",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "Class 1",
    "Parents_Name": "Shene musa and Jeinabu abou",
    "Phone_number": "670315414",
    "Location_of_child": "Binka",
    "Location_of_parents": "Binka"
  },
  {
    "No": 42,
    "Name": "Ibrahima dahiru ",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 1",
    "Parents_Name": "dahiru jibrila and Julaiyatou ouseini",
    "Phone_number": "667594175",
    "Location_of_child": "Binka",
    "Location_of_parents": "Panso"
  },
  {
    "No": 43,
    "Name": "Oumul hanni dahiru",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 1",
    "Parents_Name": "dahiru jibrila and Julaiyatou ouseini",
    "Phone_number": "667594175",
    "Location_of_child": "Panso",
    "Location_of_parents": "Panso"
  },
  {
    "No": 44,
    "Name": "Raihanatu haruna ",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 1 ",
    "Parents_Name": "haruna and hapsatu seine",
    "Phone_number": "666675807",
    "Location_of_child": "Binka",
    "Location_of_parents": "Douala"
  },
  {
    "No": 45,
    "Name": "mohamadou bouhari oumarou ",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 1 ",
    "Parents_Name": "oumarou and mairamu huseini",
    "Phone_number": "668160536",
    "Location_of_child": "Binka",
    "Location_of_parents": "Douala"
  },
  {
    "No": 46,
    "Name": "Maimunatou abdou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 5",
    "Parents_Name": "Aisatou Adamu and Abdu marijo",
    "Phone_number": "663112088",
    "Location_of_child": "Maka",
    "Location_of_parents": "Maka"
  },
  {
    "No": 47,
    "Name": "Jamilla mamuda",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 2",
    "Parents_Name": "mamuda magaji and Aisatou Babi",
    "Phone_number": "677962631",
    "Location_of_child": "Maka",
    "Location_of_parents": "Maka"
  },
  {
    "No": 48,
    "Name": "karimu mohammadou mustapha",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 4",
    "Parents_Name": "Adamu karimu and Jara Musa",
    "Phone_number": "664550878",
    "Location_of_child": "Mbosha",
    "Location_of_parents": "Mbosha"
  },
  {
    "No": 49,
    "Name": "karimu Rugaiyatou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 3",
    "Parents_Name": "Adamu karimu and Jara Musa",
    "Phone_number": "664550878",
    "Location_of_child": "Mbosha",
    "Location_of_parents": "Mbosha"
  },
  {
    "No": 50,
    "Name": "Umaru Mohammadou Mucktaru",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 4",
    "Parents_Name": "Aminatou Adamu and Adamu umaru",
    "Phone_number": "663427957",
    "Location_of_child": "Mbosha",
    "Location_of_parents": "Mbosha"
  },
  {
    "No": 51,
    "Name": "Sule Daouda",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 1",
    "Parents_Name": "Mairamu Saidou",
    "Phone_number": "###",
    "Location_of_child": "Mbosha",
    "Location_of_parents": "Mbosha"
  },
  {
    "No": 52,
    "Name": "Mohammadou Shibawaihi",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "class 3",
    "Parents_Name": "Modibo Abubakar and Halima",
    "Phone_number": "661212908",
    "Location_of_child": "Dschang",
    "Location_of_parents": "Dschang"
  },
  {
    "No": 53,
    "Name": "Faizatu Bakali",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "class 1",
    "Parents_Name": "Modibo Abubakar and Halima",
    "Phone_number": "661212908",
    "Location_of_child": "Dschang",
    "Location_of_parents": "Dschang"
  },
  {
    "No": 54,
    "Name": "Habibatu karim",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary",
    "Class": "5",
    "Parents_Name": "Abdul karim",
    "Phone_number": "677239219",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 55,
    "Name": "Maimunatu hamidu",
    "Gender": "female",
    "Type_of_education": "Arabiya",
    "Level": "",
    "Class": "",
    "Parents_Name": "Hamidu nji",
    "Phone_number": "654017796",
    "Location_of_child": "Buea",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 56,
    "Name": "Juairatu karim",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary",
    "Class": "4",
    "Parents_Name": "Abdul karim",
    "Phone_number": "677962706",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 57,
    "Name": "Fadimatu dahiru",
    "Gender": "female",
    "Type_of_education": "Arabiya",
    "Level": "",
    "Class": "",
    "Parents_Name": "Dahiru Aliyu",
    "Phone_number": "675267225",
    "Location_of_child": "Buea",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 58,
    "Name": "Isa karim",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Secondary",
    "Class": "5",
    "Parents_Name": "Abdul karim",
    "Phone_number": "666903110",
    "Location_of_child": "Buea",
    "Location_of_parents": "Buea"
  },
  {
    "No": 59,
    "Name": "Mariamu Yaya ",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "1",
    "Parents_Name": "Naphisatu hassan",
    "Phone_number": "665282941",
    "Location_of_child": "Buea",
    "Location_of_parents": "Douala"
  },
  {
    "No": 60,
    "Name": "Yougouda Salamatou",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary school",
    "Class": "Form 4",
    "Parents_Name": "Yougouda Usmanu and Fadimatou",
    "Phone_number": "650339790",
    "Location_of_child": "Yaounde",
    "Location_of_parents": "Douala"
  },
  {
    "No": 61,
    "Name": "Aishatou souaibou Ibrahim ",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "University ",
    "Class": "Third year",
    "Parents_Name": "Souaibaou Ibrahim and Balkisu Bello ",
    "Phone_number": "675704075",
    "Location_of_child": "Yaoundé ",
    "Location_of_parents": "Yaoundé "
  },
  {
    "No": 62,
    "Name": "Raihanatu Amadou ",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary ",
    "Class": "Form 4 ",
    "Parents_Name": "Amadou Issa ",
    "Phone_number": "680563232",
    "Location_of_child": "Yaoundé ",
    "Location_of_parents": "Yaoundé "
  },
  {
    "No": 63,
    "Name": "Khalida manu ",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary ",
    "Class": "Form 4 ",
    "Parents_Name": "Amadou Issa and Hawa Bello ",
    "Phone_number": "680563232",
    "Location_of_child": "Yaoundé ",
    "Location_of_parents": "Yaoundé "
  },
  {
    "No": 64,
    "Name": "Mohamadou ahamadou",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Université",
    "Class": "Thèse Doctorat PhD en science de l'ingénierie minière ",
    "Parents_Name": "Mairama Bello / Kehri hamadou umarou ",
    "Phone_number": "690821366",
    "Location_of_child": "Ngaoundere",
    "Location_of_parents": "Douala "
  },
  {
    "No": 65,
    "Name": "Idirisu Rihanatou",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Primary level",
    "Class": "Class 2",
    "Parents_Name": "Idirisu Mallam Bello",
    "Phone_number": "679 934 748",
    "Location_of_child": "Bamenda",
    "Location_of_parents": "Douala"
  },
  {
    "No": 66,
    "Name": "Alidou Humul kursumi",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary",
    "Class": "form 4 ",
    "Parents_Name": "Alidou yadi and Mairo yali",
    "Phone_number": "661080689 and 661080690",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 67,
    "Name": "Alidou Jamilatou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 4",
    "Parents_Name": "Alidou yadi and Mairo yali",
    "Phone_number": "661080690 and 661080689",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 68,
    "Name": "Alidou Hawaou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "Class 1",
    "Parents_Name": "Alidou yadi and Mairo yali",
    "Phone_number": "661080689 and 661080690",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 69,
    "Name": "Idirisu Muniratou",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "class 3 ",
    "Parents_Name": "Idrisu belo and Rasidatou sale",
    "Phone_number": "661000111",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  },
  {
    "No": 70,
    "Name": "Idirisu Raihanatou ",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "Class 3",
    "Parents_Name": "Idrisou Bello and Rasidatou sale",
    "Phone_number": "661000111",
    "Location_of_child": "Bamenda",
    "Location_of_parents": "Douala"
  },
  {
    "No": 71,
    "Name": "Shaidou Mohammadou sufianou",
    "Gender": "male",
    "Type_of_education": "Both",
    "Level": "Primary",
    "Class": "class 1",
    "Parents_Name": "Saidou yaro and Safiatou manu",
    "Phone_number": "661081888",
    "Location_of_child": "Bamenda",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 72,
    "Name": "Shaidou Hassan",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "nursery one",
    "Parents_Name": "Saidou Yaro and Safia manu",
    "Phone_number": "661081888",
    "Location_of_child": "Bamenda",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 73,
    "Name": "Shaidou Halima",
    "Gender": "female",
    "Type_of_education": "Ajamiya",
    "Level": "Primary",
    "Class": "nursery one",
    "Parents_Name": "Saidou Yaro and Safia manu",
    "Phone_number": "661081888",
    "Location_of_child": "Bamenda",
    "Location_of_parents": "Bamenda"
  },
  {
    "No": 74,
    "Name": "Ibrahim Hannatou",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary",
    "Class": "Form 2",
    "Parents_Name": "Terla ibrahim and Habsatu ",
    "Phone_number": "664044574",
    "Location_of_child": "Douala",
    "Location_of_parents": "Dschang"
  },
  {
    "No": 75,
    "Name": "Ibrahim Mohammadou",
    "Gender": "male",
    "Type_of_education": "Ajamiya",
    "Level": "Secondary",
    "Class": "upper sixth",
    "Parents_Name": "Ibrahim terla and Habsatu",
    "Phone_number": "664044574",
    "Location_of_child": "Dschang",
    "Location_of_parents": "Dschang"
  },
  {
    "No": 76,
    "Name": "Rahinatou Hassan",
    "Gender": "female",
    "Type_of_education": "Both",
    "Level": "Secondary",
    "Class": "Form 4",
    "Parents_Name": "Hadija adamu and mallam Hassan",
    "Phone_number": "661080692",
    "Location_of_child": "Douala",
    "Location_of_parents": "Douala"
  }
 ]